version: '3'

services:
    crawler:
      image: mhart/alpine-node:12
      build: .
      env_file:
        - config/.env
      depends_on:
        - mongo
    
    mongo:
      image: mongo
      ports:
        - 27017:27017
      